apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-pq-example-deployment
  labels:
    app: apollo-pq-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apollo-pq-example
  template:
    metadata:
      labels:
        app: apollo-pq-example
    spec:
      containers:
      - name: apollo-server
        image: shl0th/apollo-server-pq:0.1
        ports:
        - containerPort: 3000
      - name: apollo-client
        image: shl0th/apollo-client-pq:0.3
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: apollo-pq-example-service
spec:
  type: NodePort
  selector:
    app: apollo-pq-example
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
    - port: 4000
      targetPort: 4000
      nodePort: 30002
